### ISSUE TITLE
Option for merge commits.

### ISSUE THREAD

**Issue by xendk** [sigma/magit-gh-pulls#18]
It's a matter of taste whether one prefers merges with or without a merge commit. In my organization they're kind of expected, so it would be nice with an option to enable them with the same default message as github generates.

**Comment by mineo** [comment]
Just a quick note: setting `merge.ff` in a per-repository gitconfig to false doesn't help because https://github.com/sigma/magit-gh-pulls/blob/5f9be3359704f2d19528b5f3670c2c74a8dd295a/magit-gh-pulls.el#L302-L304 creates two merges: one for the commit to a temporary branch and one for merging the temporary branch.

**Comment by alexander-yakushev** [comment]
@xendk @mineo I've added a flag in the popup (invoked by `#`) to force creating of merge commits. You do `#`, then `- c` and then `m`. You can also `C-x C-s` to set this behavior to be the default one. I would appreciate if someone tests this and reports their experience.

**Comment by mineo** [comment]
Yep, that seems to work, thanks!

**Comment by alexander-yakushev** [comment]
Excellent! Thanks for reporting.
